### ISSUE TITLE
Doesn't build with python 3.10

### ISSUE THREAD

**Issue by rabinadk1** [masadcv/numpymaxflow#12]
# Problem

Doesn't build with python 3.10 due to `numpy==1.19.2` being in the dependencies.

# Solution
Upgrade NumPy to at least 1.21, i.e., `numpy>=1.21`

**Comment by masadcv** [comment]
Hello,
Can you please share what error you are getting when installing in python3.10?

**Comment by rabinadk1** [comment]
> Hello, Can you please share what error you are getting when installing in python3.10?

It is some kind of compilation error when building the NumPy version
